# ==============================================================
# Environment Configuration
# ==============================================================
environment:
  observation_size: 94

  action_space_type: "continuous"

  continuous_actions:
    movement_forward: [-1.0, 1.0]
    movement_strafe: [-1.0, 1.0]
    rotation: [-1.0, 1.0]
    look: [-1.0, 1.0]
    jump: [0.0, 1.0]
    place_block: [0.0, 1.0]
    remove_block: [0.0, 1.0]

  max_steps: 150

  rewards:
    seeker_visibility: 1.0 # +1 per visible hider
    hider_hidden: 1.0 # +1 when hidden
    hider_seen: -1.0 # -1 when seen

    # Optional small bonuses
    exploration: 0.1 # New cell visited (seekers)
    stationary: 0.05 # Still while hidden (hiders)
    time_penalty: -0.001 # Encourages efficiency

    # Episode end bonuses (applied once at game end)
    seeker_success: 10.0 # CHANGED from 20.0 - all hiders caught
    seeker_failure: -5.0 # CHANGED from -10.0 - time ran out
    hider_survival: 10.0 # CHANGED from 15.0 - survived
    hider_caught: -5.0 # CHANGED from -10.0 - got caught

# ==============================================================
# PPO Hyperparameters
# ==============================================================
ppo:
  lr_seeker: 0.0001
  lr_hider: 0.0001
  gamma: 0.99
  lambda: 0.95
  clip_param: 0.2
  vf_loss_coeff: 0.5
  entropy_coeff: 0.001
  train_batch_size: 4000
  minibatch_size: 128
  num_epochs: 10

  grad_clip: 0.5
  kl_coeff: 0.2
  kl_target: 0.01

  model:
    fcnet_hiddens: [128, 128, 64]
    fcnet_activation: "relu"

  num_workers: 0
  num_envs_per_worker: 1
  checkpoint_freq: 10
  checkpoint_dir: "./checkpoints"

# ==============================================================
# WebSocket Configuration
# ==============================================================
websocket:
  host: "0.0.0.0"
  port: 8765

# ==============================================================
# Training Configuration
# ==============================================================
training:
  total_episodes: 5000 # Target number of episodes
  eval_frequency: 10 # Evaluate every 10 episodes
  log_frequency: 1 # Log every episode
